module.exports={
  name: '环境监控平台',
  logindesc:'SDL 您身边的环境污染分析专家',
  prefix: 'monitorOnline',
  footerText: '环境监控平台   2017 lee',
  amapKey: 'c5cb4ec7ca3ba4618348693dd449002d',
  centerlongitude: '116.418067',
  centerlatitude: '39.930871',
  zoom: 12,
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  CORS: [],
  openPages: ['/login'],
  apiPrefix: '/mock',
  api: {
    userLogin: `/api/rest/Author/IsLogins/`,
    pollutant: `/api/rest/OutputAsPointApi/GetPollutantCodes/`,
    pollutanttype: `/api/rest/MenuInfo/GetPolluntType/`,
    realtimeOverView: `/api/rest/OutputAsPointApi/GetPointNewRealTimeDataByPollutantType/`,
    minuteOverView: `/api/rest/OutputAsPointApi/GetPointNewMinuteDataByPollutantType/`,
    hourOverView: `/api/rest/OutputAsPointApi/GetPointNewHourDataByPollutantType/`,
    dayOverView: `/api/rest/OutputAsPointApi/GetPointNewDayDataByPollutantType/`,
    monitorpoint: `/api/rest/OutputAsPointApi/GetPointsByPollutantType/`,
  },
}